### ISSUE TITLE
Use pinned hash GHA in the Test Docker Build pipeline

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-api#127]
https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L12

https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L13

https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L18

https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L18

https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L21

https://github.com/vmware/repository-service-tuf-api/blob/e40f39673c1fb7a18fdbc5fa09e69782d9663ebf/.github/workflows/test_docker_build.yml#L24

**Comment by MVrachev** [comment]
I can work on that.

**Comment by kairoaraujo** [comment]
Closed by
- #155
