### ISSUE TITLE
The Pipfile is set with a lower version from the README.

### ISSUE THREAD

**Issue by juniorlpa** [vmware/repository-service-tuf-api#130]
### Describe the bug

- The pip file is pointing to a python 3.9 version and the readme says to use >=3.10

- Pipfile
    [requires]
    python_version = "3.9"

- README 
      Development tools
       =================
       - Python >=3.10

- Once you run pipenv shell the message is returned. 

    python3 -m pipenv shell
    Warning: Python 3.9 was not found on your system...
    Neither 'pyenv' nor 'asdf' could be found to install Python.
    You can specify specific versions of Python with:
    $ pipenv --python path/to/python

### Reproduction steps

1. Check if there is no other python version installed in your system.
2. Install python 3.10
3. run pipenv shell to create the virtual environment.
...

### Expected behavior

The virtual environment must be created with the python version described in the README file which is >=3.10

**Comment by kairoaraujo** [comment]
Thank you, @juniorlpa.
Yes, I confirmed the bug. It is a good first issue.
