### ISSUE TITLE
Bug: user authorized without any scope receives all permissions

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf-api#175]
### What happened?

While testing locally I authorized myself as a user without selecting any scope.
Then I was able to execute multiple API calls even thought in their documentation it's said they require specific scope permissions.though

### What steps did you take?

1. launch a RSTUF API instance locally
2. authorize as an `admin` with password `secret` without selecting any of the scope options
3. executed successfully: `add targets`, `read config` and `check bootstrap status` commands which all require scope permissions

### What behavior did you expect?

None of the commands in step 3 should be able to be executed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
The user admin has, by default, all the scopes in its profile (It is the only user in RSTUF-API built-in).
The _try out_ from swagger documentation authenticates the user and generates the token based on his profile.

The scopes are to limit the tokens.

All tokens are generated from the user `admin` and it is a token from `admin`. However, the tokens are limited by scope.
It is similar to GitHub tokens; it generates tokens from your username but with limited scopes.

**The token**
The tokens contains the subject [id admin + randon hash] + username + password + scopes
https://github.com/vmware/repository-service-tuf-api/blob/7be4f1aeab25efca91d253cedb544ab0c566ad57/repository_service_tuf_api/token.py#L201-L205
Everything is encoded by the `TOKEN_KEY` defined by the deployment.
https://github.com/vmware/repository-service-tuf-api/blob/7be4f1aeab25efca91d253cedb544ab0c566ad57/repository_service_tuf_api/token.py#L121-L127

**Comment by MVrachev** [comment]
> The user admin has, by default, all the scopes in its profile (It is the only user in RSTUF-API built-in auth).

So, only the user `admin`, by default, all the scopes in its profile or all users are like that?

The swagger UI doesn't show that by default all scopes are selected. The UI shows that before authorization all scopes are deselected and it makes it more unclear.

**Comment by kairoaraujo** [comment]
That is correct. The swagger is more for documentation and can make as UI a bit confused.
Trying to summarize:
1. `admin` is the 'root' user for the API and has all the scopes by default
2. `admin` can generate unique tokens with limited scopes
