### ISSUE TITLE
Bug: targets require `custom` which is an optional attribute in TUF spec

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf-api#176]
### What happened?

During testing the `add targets` functionality I made a test where I removed `custom` from the default payload and executed that API call.
Because the [TUF specification about targets.json](https://theupdateframework.github.io/specification/latest/#file-formats-targets) and more precisely about the `custom` attribute in `TARGETS` defines `custom` as an optional field removing it shouldn't be a problem.
Unexpectedly to me instead of succeeding the `add targets` API call failed with Error 422.

### What steps did you take?

1. launch an RSTUF API instance locally
2. authorize as an admin with password `secret` with a scope of `write:targets`
3. click the `POST /api/v1/targets` API call 
4. Click `Try it out`
5. From the default `Request body` remove the `custom` field for one of the targets
6. Click `execute` 
7. See error `422` as a server response 

### What behavior did you expect?

Adding 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I don't think it's a valid bug, but I will check it more thoroughly. 

I tested it in my playground environment using API calls without custom keys.

This environment is using API v0.0.1a2 and worker v0.0.1a3

https://github.com/kairoaraujo/demo-package/actions/runs/3412079397/jobs/5677127732#step:4:4

**Comment by MVrachev** [comment]
Hmm, it seems to work when using GitHub actions.
Can you also try it with a local RSTUF API deployment?

**Comment by MVrachev** [comment]
I tried again with my local RSTUF API deployment and it seems that it works.
Most probably the error I saw was a JSON one.
