### ISSUE TITLE
Simplify the API payload contract design

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf-api#228]
### What is the task about?

Related to the bigger task https://github.com/vmware/repository-service-tuf/issues/23 we have decided to simplify the bootstrap process https://github.com/vmware/repository-service-tuf/issues/208.

We should remove `timestamp`, `snapshot`, `timestamp`, and `bins` roles from the API payload expected body.

### Parent feature

https://github.com/vmware/repository-service-tuf/issues/208

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by enyinna1234** [comment]
@enyinna1234 is working on this issue
