### ISSUE TITLE
Bug: service not listening on localhost:8000 after `make run-dev`

### ISSUE THREAD

**Issue by lukpueh** [vmware/repository-service-tuf-api#233]
### What happened?

Opening `http://localhost:8000/` in a browser,[ as described in "Running API development" in Readme](https://github.com/vmware/repository-service-tuf-api/blame/5731e6a86bf11a17233dc554a8b929b183f6213a/README.rst#L111), fails. Also, the docs don't make it clear what to expect.

As per docker-compose.yml, the "api" service listens on the default port `80`, and the "web" service (file server) listens on port `8080`. Should the docs maybe point to one or both of those?

### What steps did you take?

1. Followed [Readme](https://github.com/vmware/repository-service-tuf-api/blob/5731e6a86bf11a17233dc554a8b929b183f6213a/README.rst) instruction until (including)  `make run-dev`
2. Opened `http://localhost:8000/` in a browser

### What behavior did you expect?

Anything, but a failure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
I can confirm the bug.
The RSTUF API runs on `http://localhost` (`http://localhost:80`), and the TUF metadata is exposed on http://localhost:8080 after the bootstrap.

Thank you @lukpueh ! 🎉

**Comment by KAUTH** [comment]
Hey, I confirmed this too. So, the "bug" is in the `README.md` if I understand correctly. Should we just update it?

**Comment by MVrachev** [comment]
It seems that's what we need.
For anyone who wants to work on this: please check if there are other instances of `http://localhost:8000` in the repository.
For extra bonus points 😀 it will be awesome if we check that string in the RSTUF Worker repository as we can deploy RSTUF instance from there as well.

**Comment by KAUTH** [comment]
I can pick this up :smiley: 
Thanks for the pointers @MVrachev

**Comment by MVrachev** [comment]
Thank you @KAUTH that you will work on this!
