### ISSUE TITLE
Task: stop accepting information about keys in the bootstrap payload

### ISSUE THREAD

**Issue by MVrachev** [vmware/repository-service-tuf-api#260]
### What is the task about?

The things we want to do in this task are:

1. We expect to remove from the payload field `settings` the information about the keys.
This means removing this https://github.com/vmware/repository-service-tuf-api/blob/d8a745a1054d418efda67509ca57228af02f2d0b/repository_service_tuf_api/bootstrap.py#L120 structure.
2. Remove the `offline_key` flag: https://github.com/vmware/repository-service-tuf-api/blob/d8a745a1054d418efda67509ca57228af02f2d0b/repository_service_tuf_api/bootstrap.py#L132

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/207

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Closed by #262
